version: "3"

services:
    view:
        image: view:v1
        networks:
            - nir_net
        tty: true
        ports:
            - "8080:8080"
        links:
            - data_treatment
            - training
            - database

    facade:
        image: facade:v1
        networks:
            - nir_net
        tty: true
        links:
            - data_treatment
            - training
            - database

    data_treatment:
        image: data_treatment:v1
        networks:
            - nir_net
        tty: true
        links:
            - database
        volumes:
            - /home/brais/NIR-Lab/server/server/microservices/scripts/MongoDB/:/home/brais

    training:
        image: training:v1
        networks:
            - nir_net
        tty: true
        links:
            - database
        volumes:
            - /home/brais/NIR-Lab/server/server/microservices/scripts/MongoDB/:/home/brais

    database:
        image: database:v1
        networks:
            - nir_net
        tty: true
        ports:
            - "3336:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password

networks:
    nir_net:
        driver: bridge

